name: docstring-test

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  doctest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy

    - name: Check docstring using doctest
      run: |
        python3 -m doctest -v Tools/Model.py
